### PR TITLE
7128-Medic rebrand

### PR DESCRIPTION
**Pull request by latin-panda**
# Description

This PR: 
- Updates the icon of the mobile app according with the rebrand.
- Updating the app_name from Medic Mobile to Medic, copyright & license stays the same as legal name still is Medic Mobile, Inc.

Ticket: https://github.com/medic/cht-core/issues/7128
CHT-Core: https://github.com/medic/cht-core/pull/7204

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by latin-panda** [comment]
Hi @njogz, can you please review? Thanks!

**Comment by mrsarm** [comment]
Hey @latin-panda , please rebase your branch with the latest changes from `master`, I have disabled the instrumentation tests until #196 is fixed. The error in CI you got is not exactly the same but related, and will also fixed later.

**Comment by latin-panda** [comment]
@mrsarm Thank you!

@njogz PR has been updated, it's ready for review :)

**Review by njogz — APPROVED** [review]
Looks good.

**Comment by mrsarm** [comment]
Ups I merged it before moving it to AT, although it doesn't introduce any code change, just static asset changes.

There is a alpha version waiting for test, so I'm going to replace that alpha with a new one with the latest changes introduced into master with this PR.

**Comment by mrsarm** [comment]
@latin-panda I added a note about the inclusion of these PR in the release testing: https://github.com/medic/cht-android/issues/164#issuecomment-885133662

So once completed the testing we can mark this PR as verified by AT.

**Comment by ngaruko** [comment]
@latin-panda Wondering if, while we are on it, we should remove all references to `medicmobile` to use `medic`, ie things kile package name, application Id, and flavors named after medicmobile? Left a comment on #164

**Comment by latin-panda** [comment]
@ngaruko good question, I think the package name, application ID and flavors can remain the same for now it's possible to have issues with Google Play because of the current apps in the store. Some other occurrences of `medicmobile.org` are because the server instances are still using `medicmobile.org`.

**Comment by mrsarm** [comment]
@latin-panda the alpha version [passed the tests](https://github.com/medic/cht-android/issues/164#issuecomment-885361553), so you can mark this also as done in the ticket.

**Pull request merged**
