### PR TITLE
chore: change release 1.4.1 to 1.5.0

### PR DESCRIPTION
**Pull request by sugat009**
Change release 1.4.1. in CHANGELOG to 1.5.0 because there seem to be other changes than #376

### CODE REVIEW

**Comment by binokaryg** [comment]
> there seem to be other changes

Do we need to list them?

**Comment by sugat009** [comment]
@binokaryg I've added in the other changes after 1.4.0, however, the others commits did not have much info on which ticket it belonged to or are from private repos.

**Comment by binokaryg** [comment]
> @binokaryg I've added in the other changes after 1.4.0, however, the others commits did not have much info on which ticket it belonged to or are from private repos. Should I include the PR links instead?

yes, that can work

**Review by binokaryg — APPROVED** [review]
👍

**Pull request merged**
