### PR TITLE
permission reviewed

### PR DESCRIPTION
**Pull request by gagbodamakou**
To allow the Muso project and the MOH-Mali project to have photo forms, we have changed the permissions of the Android application. This was needed for an MOH project we did. Now we need the APK to be updated online.

### CODE REVIEW

**Comment by binokaryg** [comment]
@gagbodamakou please add some description on this change, or please link to a relevant issue.

**Comment by gagbodamakou** [comment]
> @gagbodamakou please add some description on this change, or please link to a relevant issue.
Hello @binokaryg ,
It is done, 
Thks

**Review by binokaryg — APPROVED** [review]
Looks good.
`secrets/secrets-moh_mali.tar.gz.enc` is it being used?

**Comment by gagbodamakou** [comment]
> Looks good. `secrets/secrets-moh_mali.tar.gz.enc` is it being used?

Yeah

**Comment by ernestoteo** [comment]
Hi @gagbodamakou, 
Please check this instruction and if you need anything let us know
`Add the flavor and make a pull request to the release branch. Once it has been approved, squash and merge the pull request, tag the commit with the same version as the last one and add a number suffix separated with a dash character (-), e.g. if the last version was v1.2.3, tag it as v1.2.3-1. In this case, it’s not necessary to publish again the reference apps in Play Store or to announce the release in the forum, if not relevant. Finally, make sure this commit is backported to the repository’s main branch.`

**Comment by gagbodamakou** [comment]
> 
Hello @ernestoteo ,
I do not understand. do you want me to include the aab/apk ?
Is it doable? please make it a little bit clear.
Thanks

**Comment by ernestoteo** [comment]
@gagbodamakou are you availlable, so we can check this one please

**Comment by gagbodamakou** [comment]
> @gagbodamakou are you availlable, so we can check this one please

Yes @ernestoteo ; i'm free.
The brand alresady. it is moh_mali. So i don't understand what you mean by "Add the flavor"

**Comment by ernestoteo** [comment]
> > @gagbodamakou are you availlable, so we can check this one please
> 
> Yes @ernestoteo ; i'm free. The brand alresady. it is moh_mali. So i don't understand what you mean by "Add the flavor"

OK fine, can I get you e-mail , I will send an invitation for a quick call ?

**Pull request merged**
