### PR TITLE
266 - Set background color as specified in resource

### PR DESCRIPTION
**Pull request by abbyad**
For #266

### CODE REVIEW

**Review by latin-panda — APPROVED** [review]
Looks good, but I'm not understanding the feature completely. 

@abbyad, We're now highlighting the training apps with red border colour, why is it important to highlight apps using `*.app.medicmobile.org` in unbranded flavor? What's the history? 🙂

Thanks!

**Comment by abbyad** [comment]
We wanted Medic-hosted deployments to use the builds (flavors) we were making for them, rather than the unbranded app, which was used frequently for testing or training. Having the border helped avoid mistakes, or alert trainers.

**Comment by abbyad** [comment]
Thanks for the review @latin-panda, and I'll leave it to you to move the issue to the right milestone and merge when appropriate.

**Comment by latin-panda** [comment]
@abbyad, do you think it makes sense to add a toast explaining why is red? Similar to when it's training app? 
"You're using Medic's instance" 
Sorry I just kept thinking on this one 😅

**Comment by abbyad** [comment]
That's a good idea. A flavor can choose to have no toast by setting the message to an empty string.

**Pull request merged**
