### PR TITLE
636 muso cdi

### PR DESCRIPTION
**Pull request by gagbodamakou**

### CODE REVIEW

**Comment by gagbodamakou** [comment]
Hello @derickl , @binokaryg 
Sorry, I have picked the wrong icons for the last commit. I fixed that.
Thank you

**Comment by derickl** [comment]
Could you please resolve the conflicts @gagbodamakou. This is blocking the build from running

**Comment by gagbodamakou** [comment]
> Could you please resolve the conflicts @gagbodamakou. This is blocking the build from running

Ok, i resolved the conflicts

**Review by derickl — APPROVED** [review]
LGTM

**Pull request merged**
